<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Primary module hooks for Red Properties module.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function red_properties_form_user_register_form_alter(array &$form, FormStateInterface &$form_state, $form_id): void {
  //var_dump($form);
  // Get landlord and tenant roles
  // Display as options in the form
  $form['user_roles'] = [
    '#type' => 'select',
    '#options' => array_map('_get_role_label', _get_customer_roles()),
    '#required' => TRUE,
    '#title' => t('What do you want to use this account for?'),
  ];
  // Ask if want to complete profile now or later.
  $form['complete_profile'] = [
    '#type' => 'checkbox',
    '#title' => t('Continue to profile setup?'),
    '#description' => t('Your profile is specific to you and helps us speed up the process of getting you into your new home. Do you wish to finish it now or later?'),
  ];

  $form['#submit'] = 'red_properties_register_submit';
}

/**
 * @return array
 */
function _get_customer_roles(): array {
  $urs = Drupal::entityTypeManager()->getStorage('user_role');
  $role_ids = $urs->getQuery()->condition('label', ['Tenant', 'Landlord'], 'IN')->execute();

  return $urs->loadMultiple($role_ids);
}

/**
 * Get label from role object
 */
function _get_role_label(&$role): string {
  return $role->label();
}

/**
 * Registration custom alter.
 */
function red_properties_register_submit(&$form, FormStateInterface &$form_state) {
  $values = $form_state->getValues(); //complete_profile, user_roles
  $obj = $form_state->getFormObject();
  dsm($obj);
  die();
}